# fly.toml app configuration file generated for teknobyen-discord-bot on 2023-09-09T17:40:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "teknobyen-discord-bot"
primary_region = "arn"

[mount]
source = "teknobyen_discord_bot_database"
destination = "/persistent_database"
